### ISSUE TITLE
Can it work with jQuery 3.1.0?

### ISSUE THREAD

**Issue by bnisevic** [ludrao/django-tellme#14]
Tellme includes jquery-1.12.2 and that results with a conflict in my base template where I load jQuery 3.1.0. The conflict manifestation is in failed use of any jQuery plugin like tooltip or slick etc. And when I remove jquery-1.12.2 reference Feedback doesn't work.

Any ideas?

Thanks!

**Comment by bnisevic** [comment]
Actually this happens only on one page where we heavily use React. So, if you have no ideas why is this you can close the issue.

Thanks again!

**Comment by ludrao** [comment]
Sorry I do not know what could cause this. Please note (though you might know already) you can override the django template so you can reference another jquery version or simply remove jquery reference for tellme. Did you try loading the same version of jquery and make sure it is loaded before feedback.js is ?

**Comment by bnisevic** [comment]
Yes, I've tried. Didn't work. I will write if I find a solution.

**Comment by ludrao** [comment]
ok thx !
