### ISSUE TITLE
Unble to cancel or goto next step after using tellme

### ISSUE THREAD

**Issue by santchanana** [ludrao/django-tellme#15]
Hello sir
I tried tellme for my local app but when i do all the step after that when i click on feedback button pop for feedback appears but after that i am unable to cancel or got next on clicking cancel or next button resepectively please help in this issue i am using python 2.7

**Comment by ludrao** [comment]
Well you should try with Python >3; I never tested against a 2.x version; Though this migth be related to javascript rather than Python. Did you try with a different browser version as well ?

**Comment by ludrao** [comment]
Closing as no feedback provided. If the issue persisted please reopen.
