### ISSUE TITLE
If not Authenticated field for email

### ISSUE THREAD

**Issue by Basiczombie** [ludrao/django-tellme#18]
This is a great app and love using it but have run into a small issue. Most of the individuals that leave feedback on our site will not be Authenticated. Could you add a field that would prompt them to leave an email address if they wish to be contacted with an update?

**Comment by ludrao** [comment]
That is a good idea indeed ! I do not have the time to look into this feature now, but I would be happy to review a pull request. This might require some changes in the upstream project that is feedback.js.
Thx

**Comment by Basiczombie** [comment]
Have sent you a pull request on this issue.

**Comment by ludrao** [comment]
Fixed by #20. Thanks @Basiczombie !
