### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by llann** [ludrao/django-tellme#21]
Plugin not working with Django 2.0

Mostly linked to news URL system

urls.py should be more something like that

```
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from .views import post_feedback


tellme_urlpatterns = [
    path('post_feedback/', post_feedback, name='post_feedback'),
]

app_name = 'tellme'
urlpatterns = [
    path('', include(tellme_urlpatterns)),
]
```
and in views.py

replace
`from django.core import urlresolvers`
with 
`from django.urls import reverse`

and

`urlresolvers.reverse('admin:tellme_feedback_change', args=(f.id,)))}`
with 
`reverse('admin:tellme_feedback_change', args=(f.id,)))}`

Sorry I really don't have time to do the PR and test it right now.

**Comment by hebertjulio** [comment]
I can doing it to learning more about Django. :)

**Comment by hebertjulio** [comment]
This import from django.views.i18n import javascript_catalog isn't used?!

**Comment by ludrao** [comment]
Hi @hebertjulio ,
Yes if you can try it and do the PR that'd be great :).
@llann and @hebertjulio  It would be good if the change is still compatible with both Django 2+ and <2.0, but not sure how that is doable. The real time consuming part is to do test it on both Django versions (1.11 and 2.0).

**Comment by hebertjulio** [comment]
Hi @ludrao 
This import from django.views.i18n import javascript_catalog isn't used? If no, I will remove this.

**Comment by ludrao** [comment]
Hi @hebertjulio , yes that seems to be a leftover from before, it should probably be cleaned.
Thx!

**Comment by ludrao** [comment]
Thx @hebertjulio, just merged your change. I'll update the readme a do a release in the coming days.

**Comment by ludrao** [comment]
OK, done ! 0.6.5 is out. Thx guys!
