### ISSUE TITLE
optipng

### ISSUE THREAD

**Issue by nordbit** [ludrao/django-tellme#3]
Please mention in docs requirement of optipng library. 
Removing shipped jquery library from tempate is not a bad idea, it conflicts with included allready in user project. It can be shipped in demo project

**Comment by ludrao** [comment]
I could not find the place where it depends on optipng lib.
Is this dependency coming from html2canvas ?

As for the template js_inc.html, it does indeed embed a default version of JQuery. There is however at least two way to override this mechanism:
- extend the js_inc.html template and redefine the {% block jquery %} to an empty block.
- or simply copy the part of the js_inc.html template that you need in your own page.

I will explicit that in the doc.

**Comment by nordbit** [comment]
Withou optipng i got error on console about missing this library, do not why, because I checked your code and see only decode encoded URI, nothin more.
