### ISSUE TITLE
text not coming correctly in admin

### ISSUE THREAD

**Issue by Shekharnunia** [ludrao/django-tellme#36]
![selection_002](https://user-images.githubusercontent.com/40422523/51466454-3e589680-1d90-11e9-8e2a-05390b38454f.png)

**Comment by Shekharnunia** [comment]
![selection_002](https://user-images.githubusercontent.com/40422523/51466398-1b2de700-1d90-11e9-90b1-f96177e4cb35.png)
sorry I forgot to upload image before

**Comment by ludrao** [comment]
I have not use django and this plugin for a while. I would not be surprised that there is some string sanitizing that prevent html content.
I will not have time to look into this, but happy to review a PR if you have a fix.

**Comment by Shekharnunia** [comment]
there is currently one pull request and I implement it and it worked correctly,  I think you should consider it.

**Comment by ludrao** [comment]
Sorry for the long long delay. There is a conflict and a question on the PR. If you want to resolve it I'd be happy to merge it.

**Comment by ludrao** [comment]
Issue was fix in PR #38
