### ISSUE TITLE
Screenshot and compression time

### ISSUE THREAD

**Issue by nordbit** [ludrao/django-tellme#4]
Screenshot do not work correctly for me, it took whole screen, compressing png file took about 2 min(sic!) in my small VPS server, effect - 35% lighter image. I can deal with 2 MB png, but not with 2 min taken from time of my server's processor

**Comment by nordbit** [comment]
Ok, I spend some time on testing under different browswers.
Best effect -Chrome from Google, it works as expected, only problem with very complicated in structure pages(many divs, js plugins)
Second - IE from MS, similar to Chrome, small issue with yours style trick "vertical-right-aligned" - do not work, button not appears.
Third and worse - newest Firefox, can not highlight area on screenshot, I don't now why, no matter page structure, complicated or simple.

Probably it is issue with html2canvas, or something else.

**Comment by ludrao** [comment]
Well I really used feedback.js and html2canvas as is. I did not had to modify anything there, so if there are browser support issue it is probably in those libs. django-tellme uses the last version of the libs, could you check with the upstream projects if that is really a bug?
That being said I tested against Firefox 45.0.1 and it worked like a charm. I haven't an easy way to test on IE right now so I cannot tell. It also works without a glitch on Chromium  49.0.2623.108.

**Comment by nordbit** [comment]
Strange, my FF is 45.02 and give me only pure screenshot, without marked area. Maybe it is graphic driver or someting else.Lets close this issue, not directly django-tellme related
