### ISSUE TITLE
Include unminified static files

### ISSUE THREAD

**Issue by thenewguy** [ludrao/django-tellme#44]
It would be appreciated if the non-minified static files sources were included in the project.

**Comment by ludrao** [comment]
I used upstream projects for the javascript part, not sure if they are still maintained. I'd be happy to merge a PR if you think this is important enough to issue a PR :)

**Comment by thenewguy** [comment]
Happy to do so.  I am a little rusty on building javascript modules.  Are you familiar?  I opened https://github.com/ivoviz/feedback/issues/72 to create a build we can drop in the project.  I am not sure off hand how to modify their package.json to produce a compatible build for direct inclusion in the page

**Comment by ludrao** [comment]
I must admit I do not recall exactly. I think the only way would be to actually try&test. Drop in should work as long as there is no incompatibilities.

**Comment by thenewguy** [comment]
I put together a clumsy action that builds the feedback script.  Turns out there wasn't much to do.  Will wait and see if upstream wants to include an official release first though (https://github.com/thenewguy/feedback/blob/deploy/.github/workflows/create-release.yml)

**Comment by thenewguy** [comment]
It seems a little heavy to add building the javascript to this project.  The newer versions of feedback on NPM have different requirements.

We should probably first upgrade to the lastest version here https://github.com/ivoviz/feedback/tree/master/development which includes the files we need
