### ISSUE TITLE
Pypi release is outdated

### ISSUE THREAD

**Issue by thenewguy** [ludrao/django-tellme#45]
Noticed the pypi release is outdated as I looked for a way to hide feedback that has been handled.  The currently released version does not properly escape html for the admin.  This all appears to be resolved in the current version so a new release would be awesome.

This app rocks btw!

![tellme-screenshot](https://user-images.githubusercontent.com/77731/107123454-a3925e00-686b-11eb-93e0-2c895a248d31.png)

**Comment by ludrao** [comment]
Release 0.6.6 done :partying_face: and uploaded on pypi
