### ISSUE TITLE
Run tests on commit

### ISSUE THREAD

**Issue by thenewguy** [ludrao/django-tellme#52]
Noticed my PR wasn't running tests.  Can we set up automated CI - github actions or something?  Would make contributions easier

**Comment by ludrao** [comment]
A previous contribution added tox to do the testing. But it has not run in a long time. I just tried and there are quite a few things to fix. Also probably worth removing old configuration?
If you are up to it go ahead :) Would could then add a github action to run the tox tests.

**Comment by thenewguy** [comment]
Would you mind making me a collaborator?  It would be easier to fix iteratively against actions.  Otherwise I will have to create a vagrant box for it

**Comment by thenewguy** [comment]
Actually I can make that work in a fork

**Comment by thenewguy** [comment]
Do you want to maintain backwards compatibility so far?  Or could we perhaps drop to django 3.0+?

**Comment by ludrao** [comment]
Sorry I am not super responsive. Yes I was thinking that maybe I should give you permission directly. As I mentioned before I spent very little time on this project in the past years and you are much more proficient than I am.
That being said I had not played with github action since their creation and I am eager to check of that works so I can set that up.

**Comment by thenewguy** [comment]
@ludrao Github actions are new to me as well.  I've tinkered with it - https://github.com/thenewguy/django-tellme/actions/runs/549424585 - This builds the fronted, shuffles the frontend files to the backend, builds and tests the backend, saves both artifacts as assets.  Concept is working - just needs some minor tweaks to work with the test matrix.  I think it is 49 test combinations for the numbers of pythons and django releases this project currently supports

**Comment by ludrao** [comment]
Great @thenewguy !
Just did my first action to publish releases, it works well. (though it is pretty simple :) )

**Comment by ludrao** [comment]
As for you other question I guess we could reduce the support to less combinations of python and django
