### ISSUE TITLE
Version 0.6.7 is currently broken

### ISSUE THREAD

**Issue by grey-shirt** [ludrao/django-tellme#66]
Django-tell me cannot be imported on version 0.6.7. 

Version 0.6.6 and below still work.

If I can be of any help please let me know, I’d really like to help! :)

**Comment by ludrao** [comment]
0.6.7 was a re-release because I thought there was a prb with 0.6.6. There is nothing new except a slightly different packaging system. We'll do a new release soon, so 0.6.7 should be ignored for now.

(maybe it is because on 0.6.7 I added an unnecessary dependency on python 3.6
