### ISSUE TITLE
Email not saved

### ISSUE THREAD

**Issue by agusmakmun** [ludrao/django-tellme#75]
I do believe the email input not saved during submission because of missing it:

https://github.com/ludrao/django-tellme/blob/master/tellme/static/tellme/vendor/feedback/feedback.js#L515-L517

```javascript
post.email = $("#feedback-user-email").val()
```

OR

```javascript
post.email = $("input[name=email]").val()
```

**Comment by ludrao** [comment]
I do not have much time to look into it but If you can do a Pull request and test it thoroughly I can merge it :sweat_smile:

**Comment by agusmakmun** [comment]
@ludrao okay then

**Comment by agusmakmun** [comment]
@ludrao I created MR #76 for this
