### ISSUE TITLE
Can i join to your transifex for make japanese translation?

### ISSUE THREAD

**Issue by salexkidd** [ludrao/django-tellme#9]
Hello @ludrao and django-tellme developers.

django-tellme is awesome django application.

Can i join to your transifex for make japanese translation? 😃

**Comment by llann** [comment]
@salexkidd I'm in charge of the transifex for the moment as @ludrao has no time to manage that for the moment. I added japanese, you can now register as a translator for this language on transifex :)

**Comment by salexkidd** [comment]
Thx you for you commi!
I prepared the Japanese translation .po file! I'll commit tomorrow to traisifex :)

**Comment by llann** [comment]
You can do it directly on Transifex :) Do you have a transifex account?

**Comment by salexkidd** [comment]
Yes I had. I sent team join request to tellme on transifex.

**Comment by llann** [comment]
Accepted :)

**Comment by salexkidd** [comment]
Thx! I try it! 👍

**Comment by kakky0312** [comment]
Hello @llann

I work with @salexkidd .
I'd like to help to translate too.

Can I?

**Comment by ludrao** [comment]
Thx guys!

When you are done, please open a pull request with the japanese translation
files so that I can integrate them in the released package.

**Comment by llann** [comment]
@kakky0312, yes you can, but it's a little project to translate ^^.

**Comment by salexkidd** [comment]
I sent PR #10  :)

**Comment by salexkidd** [comment]
Thx for releasing! I'm so happy now! 👍
